### ISSUE TITLE
Optimize the bottom navigation

### ISSUE THREAD

**Issue by aidewoode** [blackcandy-org/android#12]
Right now I just use ViewFlipper to switch the view on bottom navigation based on this issue https://github.com/hotwired/turbo-android/issues/189. But it has some problems, for example it will render all view at once including home page, and library page when after lunched the app.  And also ViewFlipper seems isn't the proper way to handle bottom navigation. So I need to find a better way to switch view for bottom navigation.

**Comment by MichalSznajder** [comment]
How did this solution (so delayed loading and swapping navHostFragments) worked comparing to using ViewFlipper ?

**Comment by aidewoode** [comment]
@michalsznajder  First of all, ViewFilpper will eagerly load all child views, which means if you have multiple views based on `TurboNavHostFragment`, you will get multiple web page requests at once when using ViewFilpper to switch views. That's unnecessary.  And second, I think using ViewFilpper for bottom navigation isn't a standard way before navigation graphs. And I also try to use nested navigation graphs to handle bottom navigation, but it didn't work with TurboNavHostFragment, that's because we need to handle `currentNavHostFragmentId` for `TurboActivityDelegate` manually. And I didn't find a way to handle this with nested navigation graphs.

Anyway, using `supportFragmentManager` is the best approach I found to deal with bottom navigation with turbo-android right now. And if you find a better solution for this problem, please let me know.
